import { Icon } from '@iconify/vue';
import { h } from 'vue';
import type { IconAliases, IconProps, IconSet } from 'vuetify';

const aliases: IconAliases = {
  collapse: 'arrow-up-01',
  complete: 'checkmark-circle-01',
  cancel: 'cancel-circle',
  close: 'cancel-01',
  delete: 'delete-02',
  clear: 'cancel-01',
  success: 'checkmark-circle-01',
  info: 'information-circle',
  warning: 'alert-02',
  error: 'cancel-circle',
  prev: 'arrow-left-01',
  next: 'arrow-right-01',
  checkboxOn: 'checkmark-square-02',
  checkboxOff: 'square',
  checkboxIndeterminate: 'minus-sign-square',
  delimiter: 'circle',
  sortAsc: 'arrow-up-01',
  sortDesc: 'arrow-down-01',
  sort: 'arrow-data-transfer-vertical',
  expand: 'arrow-down-01',
  menu: 'menu-01',
  subgroup: 'arrow-right-01',
  dropdown: 'arrow-down-01',
  radioOn: 'stop-circle',
  radioOff: 'circle',
  edit: 'pencil-edit-01',
  ratingEmpty: 'star-off',
  ratingFull: 'star',
  ratingHalf: 'star-half',
  loading: 'loading-03',
  first: 'arrow-left-double',
  last: 'arrow-right-double',
  unfold: 'arrow-expand-01',
  file: 'file-02',
  plus: 'plus-sign',
  minus: 'minus-sign',
  calendar: 'calendar-03',
  tableGroupCollapse: 'arrow-down-01',
  tableGroupExpand: 'arrow-right-01',
  // Extended Vuetify 3.7+ aliases
  treeviewCollapse: 'arrow-down-01',
  treeviewExpand: 'arrow-right-01',
  eyeDropper: 'color-picker',
  upload: 'upload-02',
  download: 'download-02',
  search: 'search-01',
  refresh: 'refresh',
  cloud: 'cloud',
  print: 'printer',
  share: 'share-08',
  lock: 'lock',
  unlock: 'unlock',
  home: 'home-01',
  color: 'color-picker',
  command: 'command',
  ctrl: 'control',
  space: 'space',
  shift: 'shift',
  option: 'option',
  enter: 'enter',
  backspace: 'backspace',
  tab: 'tab',
  capslock: 'caps-lock',
  esc: 'esc',
  alt: 'alt',
  arrowup: 'arrow-up-01',
  arrowdown: 'arrow-down-01',
  arrowleft: 'arrow-left-01',
  arrowright: 'arrow-right-01',
};

const hugeiconsSet: IconSet = {
  component: (props: IconProps) => h(Icon, { icon: `hugeicons:${props.icon}` }),
};

export { aliases, hugeiconsSet };
